SKILL_KEYWORDS = {
    "python": ["python"],
    "sql": ["sql", "postgresql", "mysql", "sqlite"],
    "fastapi": ["fastapi"],
    "docker": ["docker"],
    "aws": ["aws"],
    "pandas": ["pandas"],
    "sqlalchemy": ["sqlalchemy"],
    "pytorch": ["pytorch"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "etl": ["etl"],
    "api": ["api", "rest api", "restful api"],
    "machine-learning": ["machine learning", "ml"],
    "embeddings": ["embedding", "embeddings"],
    "faiss": ["faiss"],
    "transformers": ["transformers"],
    "nlp": ["nlp", "natural language processing"],
    "data-analysis": ["data analysis", "analytics", "dashboard"],
    "excel": ["excel"],
    "bi": ["bi", "business intelligence"],
    "docker-compose": ["docker compose", "docker-compose"],
}