SKILL_PATTERNS = {
    "python": [r"\bpython\b"],
    "sql": [r"\bsql\b"],
    "postgresql": [r"\bpostgresql\b", r"\bpostgres\b"],
    "mysql": [r"\bmysql\b"],
    "sqlite": [r"\bsqlite\b"],
    "fastapi": [r"\bfastapi\b"],
    "sqlalchemy": [r"\bsqlalchemy\b"],
    "docker": [r"\bdocker\b"],
    "aws": [r"\baws\b", r"\bamazon web services\b"],
    "pandas": [r"\bpandas\b"],
    "numpy": [r"\bnumpy\b"],
    "pytorch": [r"\bpytorch\b"],
    "scikit-learn": [r"\bscikit-learn\b", r"\bscikit learn\b", r"\bsklearn\b"],
    "etl": [r"\betl\b", r"\bextract transform load\b"],
    "machine-learning": [r"\bmachine learning\b"],
    "nlp": [r"\bnlp\b", r"\bnatural language processing\b"],
    "embeddings": [r"\bembedding\b", r"\bembeddings\b"],
    "transformers": [r"\btransformers\b", r"\btransformer\b"],
    "faiss": [r"\bfaiss\b"],
    "api": [r"\bapi\b", r"\bapis\b", r"\brest api\b", r"\brestful api\b"],
    "business-intelligence": [r"\bbusiness intelligence\b", r"\bbi\b"],
    "dashboarding": [r"\bdashboard\b", r"\bdashboards\b", r"\breporting\b"],
    "data-analysis": [r"\banalytics\b", r"\bdata analysis\b", r"\banalyst\b"],
    "excel": [r"\bexcel\b"],
    "ci-cd": [r"\bci/cd\b", r"\bci cd\b", r"\bcontinuous integration\b"],
    "cloud": [r"\bcloud\b", r"\bcloud-native\b", r"\bcloud native\b"],
    "vector-search": [r"\bvector search\b", r"\bsemantic search\b"],
}